# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cumulative sum.
#' @param x numeric vector
#' @param low lower bound
#' @param high upper bound
#' @param res bounded numeric vector
#' @export
#' @return bounded numeric vector
cumsum_bounded <- function(x, low, high) {
    .Call('genieR_cumsum_bounded', PACKAGE = 'genieR', x, low, high)
}

#' Function to calculate the loglikelihood of a constant coalescent model
#' @param N0 A population size.
#' @param t A sampling and coalescent time vector.
#' @param A A lineages vector
#' @author Simon Frost (\email{sdwfrost@@gmail.com})
#' @return Sorted sampling times, coalescent times and sampling lineages.
#' @useDynLib genieR
#' @importFrom Rcpp sourceCpp
#' @examples
#' library(ape)
#' t1=rcoal(20)
#' x=att(t1)
#' negllc_const(1, x$t, x$A)
#' @export
negllc_const <- function(N0, t, A) {
    .Call('genieR_negllc_const', PACKAGE = 'genieR', N0, t, A)
}

